---
all:
  children:
    validator:
      hosts:
        eth_validator_vm:
          ansible_host: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes"

  vars:
    # Network selection (holesky or hoodi)
    testnet_network: "hoodi"

    # Disk configuration
    disk_device: "/dev/sdb"
    mount_point: "/validator"
    filesystem: "ext4"

    # Network ports
    execution_p2p_port: 30303
    consensus_p2p_port: 9000

    # Fee recipient - MUST BE UPDATED WITH YOUR ETHEREUM ADDRESS
    fee_recipient_address: "0xdFAb85C560A0XXXXXXXXXXXXXXXXXXXXXXXXXXXX"

    # Checkpoint sync URL
    checkpoint_sync_url: "https://checkpoint-sync.hoodi.ethpandaops.io"
    # EthStaker: "https://hoodi.beaconstate.ethstaker.cc"

    # Validator graffiti
    validator_graffiti: "Ethereum Validator"

    # Validator keys availability flag
    validator_keys_available: true

    # Testing only: password used to encrypt generated keystore files
    deposit_cli_keystore_password: "98S)q2^+Gzdu+!8v" # More than 12 caracteres

    # Existing mnemonic for validator key generation (24 words)
    #deposit_cli_mnemonic: "{{ lookup('file', inventory_dir ~ '/../secure/mnemonic.txt', errors='ignore') | trim }}"
    deposit_cli_fetch_artifacts: true
    deposit_cli_force_regenerate: true
