# Ansible Inventory - Auto-generated by Terraform
# DO NOT EDIT MANUALLY - Changes will be overwritten

[validator]
${instance_ip} ansible_user=root ansible_python_interpreter=/usr/bin/python3

[validator:vars]
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[all:vars]
instance_name=${instance_name}
